apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-springboot
  template:
    metadata:
      labels:
        app: employee-springboot
    spec:
      containers:
        - name: springboot
          image: sujith2897/employee-springboot:employee-springboot
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: employee-springboot
