apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-springboot
  template:
    metadata:
      labels:
        app: employee-springboot
    spec:
      containers:
        - name: employee-springboot
          image: sujith2897/springbootdocker1
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8083
  selector:
    app: employee-springboot
